name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{secrets.MONGO_URI}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      REDIS_HOST: ${{secrets.REDIS_HOST}}
      REDIS_PORT: ${{secrets.REDIS_PORT}}
      REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
      REDIS_TLS: ${{secrets.REDIS_TLS}}
      NODE_ENV: 'test'

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
