name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

        env:
          MONGO_URI: ${{secrets.MONGO_URI}}
          JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
